app:
  datasource:
    url: jdbc:postgresql://localhost:5436/crmupload-appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  billing:
    work-dir: /home/ralf/tmp

spring:
  main:
    web-application-type: none

logging:
  level:
    org.apache.pdfbox.pdmodel.font: ERROR