app:
  datasource:
    url: jdbc:postgresql://app-db:5432/crmupload-appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  billing:
    invoice-dir: /data/invoices

spring:
  main:
    web-application-type: none

logging:
  level:
    org.apache.pdfbox.pdmodel.font: ERROR