server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://dev-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Containername übernehmen
      - source_labels: [__meta_docker_container_name]
        target_label: container

      # Host/Umgebung fest markieren
      - target_label: env
        replacement: dev

      # === HIER DIE MAGIE ===
      # gpu-prod explizit ausschließen
      - source_labels: [__meta_docker_container_name]
        regex: crmupload-worker-duplicate-check-gpu-prod
        action: drop
