app:
  activation:
    base-url: http://localhost:8086
    uri: /auth/activate

spring:
  mail:
    host: crmupload-mailpit
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
