server:
  port: 8086

app:
  datasource:
    url: jdbc:postgresql://app-db:5432/crmupload-appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  consumer-upload:
    poll-interval-ms: 10000
    batch-size: 5

  jwt:
    secret: "eine-lange-zuf√§llige-zeichenkette-hier-eintragen-32+Zeichen"
    expiration-ms: 3600000   # 1 Stunde