app:
  datasource:
    url: jdbc:postgresql://localhost:5436/crmupload-appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  maintenance:
    base-url: http://localhost:8086
    workdir: /home/ralf/tmp

spring:
  main:
    web-application-type: none