app:
  datasource:
    url: jdbc:postgresql://crmupload-db:5432/crmupload-appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  consumer-upload:
    poll-interval-ms: 10000
    batch-size: 5
    workdir: /data/tmp

spring:
  main:
    web-application-type: none
  mail:
    host: crmupload-mailpit
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

ctx:

  bexio:
    accountType:
      - Customer
      - Investor
      - Partner
      - Reseller

    mappings:
      accountType:
        Kunden: Customer
        Partner: Partner

  myexcel:
    accountType:
      - Customer
      - Investor
      - Partner
      - Reseller

    accountPhoneType:
      - Office
      - Mobile
      - Fax
      - Other

    industry:
      - Consulting
      - Software
      - Manufacturing
      - Retail
      - Construction

    contactSalutationName:
      - Mr.
      - Ms.
      - Mrs.
      - Dr.

    contactPhoneType:
      - Office
      - Mobile
      - Fax
      - Home
      - Other

    mappings:

      accountType:
        Kunde: Customer
        Weiterverkaeufer: Reseller

      accountPhoneType:
        Buero: Office
        Handy: Mobile
        Sonstige: Other

      industry:
        Beratung: Consulting
        Software: Software
        Fertigung: Manufacturing
        Handel: Retail
        Produktion: Construction

      contactSalutationName:
        Herr: Mr.
        Frau: Ms.

      contactPhoneType:
        Buero: Office
        Handy: Mobile
        Privat: Home
        Sonstige: Other
