server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Containername (ohne Slash)
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container

      # Umgebung fest auf PROD
      - target_label: env
        replacement: prod

      # Optional: Service-Name (hilfreich in Grafana)
      - source_labels: [__meta_docker_container_name]
        regex: "/(crmupload-[^_]+).*"
        target_label: service
        replacement: "$1"

      # gpu-prod explizit ausschlie√üen
      - source_labels: [__meta_docker_container_name]
        regex: "/crmupload-worker-duplicate-check-gpu-prod"
        action: drop
